language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install:
  - pip install -e .
  - pip install -r registration/tests/requirements.txt
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
script: make test
